name: Build TrollTools

on:
  push:
    branches: 
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build TrollTools
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Theos
        uses: Randomblock1/theos-action@v1.1
      - name: build
        run: ./build.command
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: TrollTools.tipa
          path: /Users/runner/work/${{github.event.repository.name}}/${{github.event.repository.name}}/build/TrollTools.tipa
